/**
 * index.js
 */

import React, { useState } from "react";

import Head from "next/head";
import type { NextPage } from "next";

import dynamic from "next/dynamic";
const Index = dynamic(() => import("../components/index"), { ssr: false });

const IndexPage: NextPage = () => {

    return (<>
        <Head>
            <title>SPC Tree of Giving</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Index />
    </>);

};

export default IndexPage;
